services:
  app:
    image: dedski-airtable:latest
    build:
      context: ./
      args:
        USER_GRUP: ${USER_GRUP}
        USER_NAME: ${USER_NAME}
        USER_PASW: ${USER_PASW}
        ROOTS_GID: ${ROOTS_GID}
        ROOTS_UID: ${ROOTS_UID}
    volumes:
      - ./:/opt/app
    env_file:
      - .env
    command: ruby script.rb

networks:
  default:
    name: dedski
    ipam:
      driver: default
      config:
        - subnet: "69.0.0.0/24"
