name: airtable

on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - synchronize
      - closed
      - reopened
      - edited
      - assigned
      - unassigned
      - review_requested
      - review_request_removed

jobs:
  update_merge_request_table:
    name: Airtable-Integrations
    uses: aevula/airtable-integrations/.github/workflows/base.yml@master
    with:
      component: Airtable-Integrations
